# **Import** **Libraries**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
raw_data=pd.read_csv("/content/sample_data/swiftchain_logistics_450k.csv")

Basic Information of dataset

In [ ]:
raw_data.shape

(450800, 28)

**Phase1 ---EDA Analysis---**

In [5]:
print("info:",raw_data.info())
print("describe:",raw_data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450800 entries, 0 to 450799
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Shipment_ID             450800 non-null  object
 1   Order_Date              450800 non-null  object
 2   Promised_Delivery_Date  450800 non-null  object
 3   Actual_Delivery_Date    437103 non-null  object
 4   Delay_Days              437103 non-null  float64
 5   Delay_Status            437103 non-null  object
 6   On_Time_Flag            437103 non-null  float64
 7   Origin_City             450800 non-null  object
 8   Origin_State            450800 non-null  object
 9   Origin_Region           450800 non-null  object
 10  Destination_City        450800 non-null  object
 11  Destination_State       450800 non-null  object
 12  Destination_Region      450800 non-null  object
 13  Route_ID                450800 non-null  object
 14  Distance_Miles          450800 non-null  int64
 15  Warehouse_ID            450800 non-null  object
 16  Warehouse_City          450800 non-null  object
 17  Warehouse_State         450800 non-null  object
 18  Carrier                 450800 non-null  object
 19  Ship_Mode               450800 non-null  object
 20  Product_Category        450800 non-null  object
 21  Product_Weight_kg       450800 non-null  float64
 22  Order_Value             450800 non-null  float64
 23  Shipping_Cost           450800 non-null  float64
 24  Customer_Segment        450800 non-null  object
 25  Customer_ID             450800 non-null  object
 26  Weather_Condition       428093 non-null  object
 27  Traffic_Condition       432580 non-null  object
dtypes: float64(5), int64(1), object(22)
memory usage: 96.3+ MB
info: None
describe:           Delay_Days   On_Time_Flag  Distance_Miles  Product_Weight_kg  \
count  437103.000000  437103.000000   450800.000000      450800.000000
mean        4.032411       0.488722     1523.828445         249.813767
std         7.217166       0.499873      852.265047         144.335672
min        -3.000000       0.000000       50.000000           0.500000
25%        -1.000000       0.000000      785.000000         124.757500
50%         2.000000       0.000000     1526.000000         249.620000
75%         9.000000       1.000000     2261.000000         375.070000
max        64.000000       1.000000     3000.000000         500.000000

         Order_Value  Shipping_Cost
count  450800.000000  450800.000000
mean     7503.103057     138.032050
std      4323.008862     133.344229
min        20.030000      10.060000
25%      3763.042500      53.130000
50%      7501.960000      89.960000
75%     11245.852500     166.370000
max     14999.950000     871.870000

By seeing above info we can see clearly **nulls in dataset**(Actual_Delivery_Date,Delay_Days,Delay_Status ,On_Time_Flag,Weather_Condition,Traffic_Condition) &(Actual_Delivery_Date,Promised_Delivery_Date,Order_Date are **object type**)

In [10]:
raw_data.duplicated().sum()

np.int64(800)

From above we can see that we have **duplicates** in data

In [6]:
raw_data.columns

Index(['Shipment_ID', 'Order_Date', 'Promised_Delivery_Date',
       'Actual_Delivery_Date', 'Delay_Days', 'Delay_Status', 'On_Time_Flag',
       'Origin_City', 'Origin_State', 'Origin_Region', 'Destination_City',
       'Destination_State', 'Destination_Region', 'Route_ID', 'Distance_Miles',
       'Warehouse_ID', 'Warehouse_City', 'Warehouse_State', 'Carrier',
       'Ship_Mode', 'Product_Category', 'Product_Weight_kg', 'Order_Value',
       'Shipping_Cost', 'Customer_Segment', 'Customer_ID', 'Weather_Condition',
       'Traffic_Condition'],
      dtype='object')

So we have nulls and duplicates according to bussiness rule:nulls in (Actual_Delivery_Date,Delay_Days,Delay_Status ,On_Time_Flag) we are separating **into intransit.csv**. Weather_Condition
Traffic_Condition are filled by **"Unknown"**

In [11]:
in_transit=raw_data.loc[raw_data["Actual_Delivery_Date"].isnull()]
in_transit.to_csv("intransit.csv",index=False)
raw_data.drop(in_transit.index,inplace=True)
raw_data.drop_duplicates(inplace=True)

In [18]:
raw_data.isnull().sum().reset_index()

                     index      0
0              Shipment_ID      0
1               Order_Date      0
2   Promised_Delivery_Date      0
3     Actual_Delivery_Date      0
4               Delay_Days      0
5             Delay_Status      0
6             On_Time_Flag      0
7              Origin_City      0
8             Origin_State      0
9            Origin_Region      0
10        Destination_City      0
11       Destination_State      0
12      Destination_Region      0
13                Route_ID      0
14          Distance_Miles      0
15            Warehouse_ID      0
16          Warehouse_City      0
17         Warehouse_State      0
18                 Carrier      0
19               Ship_Mode      0
20        Product_Category      0
21       Product_Weight_kg      0
22             Order_Value      0
23           Shipping_Cost      0
24        Customer_Segment      0
25             Customer_ID      0
26       Weather_Condition  21945
27       Traffic_Condition  17612

Still we have nulls in Weather_Condition:21945
Traffic_Condition:17612 so we are filling with "Unknown"

In [27]:
raw_data['Weather_Condition']=raw_data['Weather_Condition'].fillna("Unknown")
raw_data['Traffic_Condition']=raw_data['Traffic_Condition'].fillna("Unknown")
print(f" nulls:{raw_data.isnull().sum()},dupicates:{raw_data.duplicated().sum()},shape:{raw_data.shape}")

 nulls:Shipment_ID               0
Order_Date                0
Promised_Delivery_Date    0
Actual_Delivery_Date      0
Delay_Days                0
Delay_Status              0
On_Time_Flag              0
Origin_City               0
Origin_State              0
Origin_Region             0
Destination_City          0
Destination_State         0
Destination_Region        0
Route_ID                  0
Distance_Miles            0
Warehouse_ID              0
Warehouse_City            0
Warehouse_State           0
Carrier                   0
Ship_Mode                 0
Product_Category          0
Product_Weight_kg         0
Order_Value               0
Shipping_Cost             0
Customer_Segment          0
Customer_ID               0
Weather_Condition         0
Traffic_Condition         0
dtype: int64,dupicates:0,shape:(436328, 28)

From above we have no nulls and dupilicates and dataset shape changed

In [23]:
for i in raw_data.columns:
  print(f"{i} :{raw_data[i].nunique()}")

Shipment_ID :436328
Order_Date :1461
Promised_Delivery_Date :1470
Actual_Delivery_Date :1519
Delay_Days :68
Delay_Status :5
On_Time_Flag :2
Origin_City :24
Origin_State :22
Origin_Region :4
Destination_City :24
Destination_State :22
Destination_Region :4
Route_ID :200
Distance_Miles :2951
Warehouse_ID :10
Warehouse_City :10
Warehouse_State :9
Carrier :5
Ship_Mode :4
Product_Category :8
Product_Weight_kg :49947
Order_Value :378584
Shipping_Cost :55321
Customer_Segment :3
Customer_ID :8000
Weather_Condition :6
Traffic_Condition :5

**Now Main analysis "Why delay is happening"**

In [33]:
Ontimepercent=raw_data.groupby(["On_Time_Flag"]).agg(
    total_orders=("On_Time_Flag","count")).reset_index()
Ontimepercent["deliverytime%"]=round(Ontimepercent['total_orders']/Ontimepercent['total_orders'].sum()*100,2)
print(Ontimepercent)

   On_Time_Flag  total_orders  deliverytime%
0           0.0        223098          51.13
1           1.0        213230          48.87

According to above info we on time delivery precentage is 48.87% and delay delivery percentage is 51.15%. So ontime is less than industry level 85% so we to find which causing delay

so i am starting from basic analayis( who what where and why),by seeing data i know some([Warehouse_ID,Product_Category,Carrier,Weather_Condition,Traffic_Condition,Ship_Mode,Distance_Miles])

In [53]:
cols=["Warehouse_ID","Product_Category","Carrier","Weather_Condition","Traffic_Condition","Ship_Mode","Route_ID","Origin_Region","Destination_Region"]
for i in cols:
  info= raw_data.groupby([i]).agg(
     Total_orders=("Shipment_ID","count"),
     ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
     delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
    ).reset_index()
  info["ontime_per"]=round(info['ontime_orders']/info['Total_orders']*100,2)
  info["delayed_per"]=round(info['delayed_orders']/info['Total_orders']*100,2)
  print(info.sort_values(ascending=True,by="ontime_per"))

  Warehouse_ID  Total_orders  ontime_orders  delayed_orders  ontime_per  \
1       WH-002         43379          15071           28308       34.74
7       WH-008         43449          15138           28311       34.84
4       WH-005         43552          15300           28252       35.13
3       WH-004         43184          23512           19672       54.45
0       WH-001         43697          23837           19860       54.55
5       WH-006         43654          23903           19751       54.76
2       WH-003         43697          23955           19742       54.82
9       WH-010         43946          24095           19851       54.83
6       WH-007         43573          23973           19600       55.02
8       WH-009         44197          24446           19751       55.31

   delayed_per
1        65.26
7        65.16
4        64.87
3        45.55
0        45.45
5        45.24
2        45.18
9        45.17
6        44.98
8        44.69
   Product_Category  Total_orders  ontime_orders  delayed_orders  ontime_per  \
7   Pharmaceuticals         52543          24124           28419       45.91
2       Electronics         87154          40025           47129       45.92
6  Medical Supplies         34927          16086           18841       46.06
0           Apparel         52279          26448           25831       50.59
5        Industrial         43804          22221           21583       50.73
3   Food & Beverage         56741          28825           27916       50.80
4         Furniture         65138          33201           31937       50.97
1        Automotive         43742          22300           21442       50.98

   delayed_per
7        54.09
2        54.08
6        53.94
0        49.41
5        49.27
3        49.20
4        49.03
1        49.02
  Carrier  Total_orders  ontime_orders  delayed_orders  ontime_per  \
0     DHL         65444          24172           41272       36.94
4    USPS         87714          40206           47508       45.84
2  OnTrac         43706          21855           21851       50.00
3     UPS        117887          60559           57328       51.37
1   FedEx        121577          66438           55139       54.65

   delayed_per
0        63.06
4        54.16
2        50.00
3        48.63
1        45.35
  Weather_Condition  Total_orders  ontime_orders  delayed_orders  ontime_per  \
2              Rain         82864          40365           42499       48.71
0             Clear        227944         111346          116598       48.85
1               Fog         41371          20234           21137       48.91
4             Storm         20850          10198           10652       48.91
3              Snow         41354          20304           21050       49.10
5           Unknown         21945          10783           11162       49.14

   delayed_per
2        51.29
0        51.15
1        51.09
4        51.09
3        50.90
5        50.86
  Traffic_Condition  Total_orders  ontime_orders  delayed_orders  ontime_per  \
4           Unknown         17612           8539            9073       48.48
3            Severe         41989          20454           21535       48.71
2            Medium        146772          71600           75172       48.78
0              High        104771          51308           53463       48.97
1               Low        125184          61329           63855       48.99

   delayed_per
4        51.52
3        51.29
2        51.22
0        51.03
1        51.01
  Ship_Mode  Total_orders  ontime_orders  delayed_orders  ontime_per  \
2    Ground        174838          85215           89623       48.74
1   Express         86786          42477           44309       48.94
3  Standard        109415          53547           55868       48.94
0       Air         65289          31991           33298       49.00

   delayed_per
2        51.26
1        51.06
3        51.06
0        51.00
    Route_ID  Total_orders  ontime_orders  delayed_orders  ontime_per  \
108  RT-0109          2156            701            1455       32.51
35   RT-0036          2081            695            1386       33.40
7    RT-0008          2249            760            1489       33.79
188  RT-0189          2225            754            1471       33.89
23   RT-0024          2154            734            1420       34.08
..       ...           ...            ...             ...         ...
36   RT-0037          2207           1154            1053       52.29
71   RT-0072          2265           1185            1080       52.32
194  RT-0195          2216           1170            1046       52.80
1    RT-0002          2208           1171            1037       53.03
90   RT-0091          2233           1201            1032       53.78

     delayed_per
108        67.49
35         66.60
7          66.21
188        66.11
23         65.92
..           ...
36         47.71
71         47.68
194        47.20
1          46.97
90         46.22

[200 rows x 6 columns]
  Origin_Region  Total_orders  ontime_orders  delayed_orders  ontime_per  \
2         South         95803          46792           49011       48.84
0       Central         87341          42684           44657       48.87
3          West        122072          59659           62413       48.87
1          East        131112          64095           67017       48.89

   delayed_per
2        51.16
0        51.13
3        51.13
1        51.11
  Destination_Region  Total_orders  ontime_orders  delayed_orders  ontime_per  \
1               East        130780          63631           67149       48.65
2              South         95945          46915           49030       48.90
0            Central         86911          42504           44407       48.91
3               West        122692          60180           62512       49.05

   delayed_per
1        51.35
2        51.10
0        51.09
3        50.95

see in warehouse ontime% is 32 lowest(wh-002,wh-005,wh-008) the main issues warehouses.Carrier (DHL:37,Usps:46) so we have look into too,**main problem is Pharmaceuticals is getting delayed**. we also have route problem.

First we have find which warehouse and region warehouse causing problem:

In [60]:
warehouses=raw_data.groupby(["Warehouse_ID","Origin_Region"]).agg(
    total_orders=("Warehouse_ID","count"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())).reset_index()
warehouses["ontime_per"]=round(warehouses['ontime_orders']/warehouses['total_orders']*100,2)
warehouses["delayed_per"]=round(warehouses['delayed_orders']/warehouses['total_orders']*100,2)
warehouses.sort_values(ascending=True,by="ontime_per")

,Warehouse_ID,Origin_Region,total_orders,ontime_orders,delayed_orders,ontime_per,delayed_per
6,WH-002,South,9518,3246,6272,34.10,65.90
17,WH-005,East,12886,4453,8433,34.56,65.44
5,WH-002,East,13131,4542,8589,34.59,65.41
31,WH-008,West,12179,4218,7961,34.63,65.37
29,WH-008,East,12996,4512,8484,34.72,65.28
28,WH-008,Central,8662,3025,5637,34.92,65.08
4,WH-002,Central,8651,3028,5623,35.00,65.00
18,WH-005,South,9505,3332,6173,35.06,64.94
30,WH-008,South,9612,3383,6229,35.20,64.80
7,WH-002,West,12079,4255,7824,35.23,64.77
19,WH-005,West,12343,4367,7976,35.38,64.62
16,WH-005,Central,8818,3148,5670,35.70,64.30
20,WH-006,Central,8655,4671,3984,53.97,46.03
15,WH-004,West,11908,6461,5447,54.26,45.74
0,WH-001,Central,8644,4696,3948,54.33,45.67
12,WH-004,Central,8778,4771,4007,54.35,45.65
8,WH-003,Central,8616,4690,3926,54.43,45.57
14,WH-004,South,9506,5174,4332,54.43,45.57
2,WH-001,South,9521,5195,4326,54.56,45.44
23,WH-006,West,12302,6713,5589,54.57,45.43
1,WH-001,East,13319,7269,6050,54.58,45.42
37,WH-010,East,13217,7224,5993,54.66,45.34
3,WH-001,West,12213,6677,5536,54.67,45.33
13,WH-004,East,12992,7106,5886,54.70,45.30
9,WH-003,East,13191,7221,5970,54.74,45.26
22,WH-006,South,9587,5254,4333,54.80,45.20
36,WH-010,Central,8690,4767,3923,54.86,45.14
38,WH-010,South,9679,5310,4369,54.86,45.14
35,WH-009,West,12293,6752,5541,54.93,45.07
25,WH-007,East,13026,7155,5871,54.93,45.07
39,WH-010,West,12360,6794,5566,54.97,45.03
11,WH-003,West,12174,6695,5479,54.99,45.01
26,WH-007,South,9547,5251,4296,55.00,45.00
27,WH-007,West,12221,6727,5494,55.04,44.96
10,WH-003,South,9716,5349,4367,55.05,44.95
34,WH-009,South,9612,5298,4314,55.12,44.88
24,WH-007,Central,8779,4840,3939,55.13,44.87
21,WH-006,East,13110,7265,5845,55.42,44.58
33,WH-009,East,13244,7348,5896,55.48,44.52
32,WH-009,Central,9048,5048,4000,55.79,44.21

We found that warehouse is main reason it does not depend on region. now focus on carrier

In [65]:
carrier=raw_data.groupby(["Carrier"]).agg(
    total_orders=("Carrier","count"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
carrier["ontime_per"]=round(carrier['ontime_orders']/carrier['total_orders']*100,2)
carrier["delayed_per"]=round(carrier['delayed_orders']/carrier['total_orders']*100,2)

In [68]:
print(carrier.sort_values(ascending=True,by="ontime_per"))

  Carrier  total_orders  ontime_orders  delayed_orders  ontime_per  \
0     DHL         65444          24172           41272       36.94
4    USPS         87714          40206           47508       45.84
2  OnTrac         43706          21855           21851       50.00
3     UPS        117887          60559           57328       51.37
1   FedEx        121577          66438           55139       54.65

   delayed_per
0        63.06
4        54.16
2        50.00
3        48.63
1        45.35

Base on above info DHL and usps is main problem, we imporve these two we can improve overall percent or assign orders to fedex is better.

Now combine both warehouses and carrier

In [82]:
warehouses_carriers=raw_data.groupby(["Warehouse_ID","Carrier"]).agg(
    total_orders=("Shipment_ID","count"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
warehouses_carriers["ontime_per"]=round(warehouses_carriers['ontime_orders']/warehouses_carriers['total_orders']*100,2)
warehouses_carriers["delayed_per"]=round(warehouses_carriers['delayed_orders']/warehouses_carriers['total_orders']*100,2)

warehouses_carriers.sort_values(ascending=True,by="ontime_per")

def classify(ontime_per):
  if ontime_per<40:
    return "ClassC","Critical"

  elif ontime_per>=40 and ontime_per<=50:
    return "ClassB","Watch"

  else:
    return "ClassA","Excellent"
warehouses_carriers[["class","Performance"]]=warehouses_carriers["ontime_per"].apply(lambda x:pd.Series(classify(x)))

warehouses_carriers.sort_values(ascending=True,by="ontime_per")

,Warehouse_ID,Carrier,total_orders,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per,class,Performance
20,WH-005,DHL,6642,7488.673528,133.926939,1649,4993,24.83,75.17,ClassC,Critical
5,WH-002,DHL,6485,7511.810244,136.953062,1634,4851,25.20,74.80,ClassC,Critical
35,WH-008,DHL,6586,7534.577083,137.441297,1686,4900,25.60,74.40,ClassC,Critical
39,WH-008,USPS,8621,7495.187180,136.623843,2673,5948,31.01,68.99,ClassC,Critical
9,WH-002,USPS,8651,7534.979060,136.934402,2709,5942,31.31,68.69,ClassC,Critical
24,WH-005,USPS,8794,7461.065650,137.268129,2903,5891,33.01,66.99,ClassC,Critical
7,WH-002,OnTrac,4357,7499.782447,137.947165,1527,2830,35.05,64.95,ClassC,Critical
37,WH-008,OnTrac,4265,7438.714851,137.126014,1511,2754,35.43,64.57,ClassC,Critical
38,WH-008,UPS,11865,7459.944592,136.350013,4318,7547,36.39,63.61,ClassC,Critical
22,WH-005,OnTrac,4369,7489.702456,137.059169,1610,2759,36.85,63.15,ClassC,Critical
23,WH-005,UPS,11747,7534.629864,136.077347,4330,7417,36.86,63.14,ClassC,Critical
8,WH-002,UPS,11807,7491.327472,138.311336,4374,7433,37.05,62.95,ClassC,Critical
6,WH-002,FedEx,12079,7545.534307,138.634747,4827,7252,39.96,60.04,ClassC,Critical
21,WH-005,FedEx,12000,7546.495701,138.275778,4808,7192,40.07,59.93,ClassB,Watch
36,WH-008,FedEx,12112,7470.873202,138.111195,4950,7162,40.87,59.13,ClassB,Watch
15,WH-004,DHL,6532,7487.496549,135.977610,2682,3850,41.06,58.94,ClassB,Watch
0,WH-001,DHL,6559,7486.987196,134.662863,2718,3841,41.44,58.56,ClassB,Watch
10,WH-003,DHL,6460,7395.693972,135.829847,2719,3741,42.09,57.91,ClassB,Watch
45,WH-010,DHL,6507,7501.766010,139.131328,2741,3766,42.12,57.88,ClassB,Watch
30,WH-007,DHL,6496,7502.405182,138.679711,2741,3755,42.20,57.80,ClassB,Watch
25,WH-006,DHL,6540,7660.084265,137.951934,2766,3774,42.29,57.71,ClassB,Watch
40,WH-009,DHL,6637,7626.477945,140.030872,2836,3801,42.73,57.27,ClassB,Watch
4,WH-001,USPS,8960,7540.343215,139.031886,4585,4375,51.17,48.83,ClassA,Excellent
14,WH-003,USPS,8754,7573.743920,137.659488,4504,4250,51.45,48.55,ClassA,Excellent
34,WH-007,USPS,8748,7536.564815,138.062370,4507,4241,51.52,48.48,ClassA,Excellent
49,WH-010,USPS,8873,7439.971082,136.561364,4583,4290,51.65,48.35,ClassA,Excellent
19,WH-004,USPS,8664,7489.457163,137.547313,4498,4166,51.92,48.08,ClassA,Excellent
29,WH-006,USPS,8802,7580.452958,138.347305,4605,4197,52.32,47.68,ClassA,Excellent
44,WH-009,USPS,8847,7457.018446,138.802613,4639,4208,52.44,47.56,ClassA,Excellent
27,WH-006,OnTrac,4420,7523.581916,141.313342,2420,2000,54.75,45.25,ClassA,Excellent
12,WH-003,OnTrac,4404,7529.477548,135.485817,2431,1973,55.20,44.80,ClassA,Excellent
17,WH-004,OnTrac,4382,7559.642469,138.697549,2435,1947,55.57,44.43,ClassA,Excellent
42,WH-009,OnTrac,4359,7451.926797,136.934769,2437,1922,55.91,44.09,ClassA,Excellent
2,WH-001,OnTrac,4249,7637.601525,140.963770,2390,1859,56.25,43.75,ClassA,Excellent
18,WH-004,UPS,11523,7534.882332,139.148783,6568,4955,57.00,43.00,ClassA,Excellent
32,WH-007,OnTrac,4388,7379.154043,138.675672,2511,1877,57.22,42.78,ClassA,Excellent
47,WH-010,OnTrac,4513,7468.188626,138.260716,2583,1930,57.23,42.77,ClassA,Excellent
28,WH-006,UPS,11733,7389.576241,137.639634,6722,5011,57.29,42.71,ClassA,Excellent
3,WH-001,UPS,11744,7514.824503,137.548773,6756,4988,57.53,42.47,ClassA,Excellent
33,WH-007,UPS,11830,7508.677007,138.706322,6830,5000,57.73,42.27,ClassA,Excellent
48,WH-010,UPS,11861,7536.665768,138.782432,6852,5009,57.77,42.23,ClassA,Excellent
43,WH-009,UPS,11956,7449.648939,138.143142,6942,5014,58.06,41.94,ClassA,Excellent
13,WH-003,UPS,11821,7497.619952,138.449273,6867,4954,58.09,41.91,ClassA,Excellent
46,WH-010,FedEx,12192,7529.136568,138.691751,7336,4856,60.17,39.83,ClassA,Excellent
1,WH-001,FedEx,12185,7478.390475,139.618332,7388,4797,60.63,39.37,ClassA,Excellent
11,WH-003,FedEx,12258,7496.045804,139.875252,7434,4824,60.65,39.35,ClassA,Excellent
16,WH-004,FedEx,12083,7453.816335,137.410771,7329,4754,60.66,39.34,ClassA,Excellent
26,WH-006,FedEx,12159,7500.509150,139.372501,7390,4769,60.78,39.22,ClassA,Excellent
31,WH-007,FedEx,12111,7586.116873,138.513660,7384,4727,60.97,39.03,ClassA,Excellent
41,WH-009,FedEx,12398,7489.214478,139.039363,7592,4806,61.24,38.76,ClassA,Excellent

In [87]:
warehouses_carriers_products=raw_data.groupby(["Warehouse_ID","Carrier","Product_Category"]).agg(
    total_orders=("Shipment_ID","count"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
warehouses_carriers_products["ontime_per"]=round(warehouses_carriers_products['ontime_orders']/warehouses_carriers_products['total_orders']*100,2)
warehouses_carriers_products["delayed_per"]=round(warehouses_carriers_products['delayed_orders']/warehouses_carriers_products['total_orders']*100,2)

warehouses_carriers_products.sort_values(ascending=True,by="ontime_per")

def classify(ontime_per):
  if ontime_per<40:
    return "ClassC","Critical"

  elif ontime_per>=40 and ontime_per<=50:
    return "ClassB","Watch"

  else:
    return "ClassA","Excellent"
warehouses_carriers_products[["class","Performance"]]=warehouses_carriers_products["ontime_per"].apply(lambda x:pd.Series(classify(x)))

warehouses_carriers_products.sort_values(ascending=True,by="ontime_per").head(60)

,Warehouse_ID,Carrier,Product_Category,total_orders,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per,class,Performance
47,WH-002,DHL,Pharmaceuticals,779,7444.251489,140.475469,151,628,19.38,80.62,ClassC,Critical
286,WH-008,DHL,Medical Supplies,516,7272.275233,136.130174,111,405,21.51,78.49,ClassC,Critical
167,WH-005,DHL,Pharmaceuticals,812,7491.534052,129.865899,181,631,22.29,77.71,ClassC,Critical
162,WH-005,DHL,Electronics,1277,7282.317400,126.618504,289,988,22.63,77.37,ClassC,Critical
42,WH-002,DHL,Electronics,1253,7457.516433,133.061341,286,967,22.83,77.17,ClassC,Critical
45,WH-002,DHL,Industrial,642,7739.398302,140.487056,147,495,22.90,77.10,ClassC,Critical
166,WH-005,DHL,Medical Supplies,532,7075.447914,139.295526,122,410,22.93,77.07,ClassC,Critical
282,WH-008,DHL,Electronics,1332,7616.362267,140.741149,324,1008,24.32,75.68,ClassC,Critical
287,WH-008,DHL,Pharmaceuticals,780,7477.980013,143.523051,194,586,24.87,75.13,ClassC,Critical
281,WH-008,DHL,Automotive,642,7526.459626,132.365358,160,482,24.92,75.08,ClassC,Critical
285,WH-008,DHL,Industrial,660,7640.518439,130.209197,165,495,25.00,75.00,ClassC,Critical
165,WH-005,DHL,Industrial,694,7506.402478,146.484063,174,520,25.07,74.93,ClassC,Critical
46,WH-002,DHL,Medical Supplies,512,7521.453906,133.325332,131,381,25.59,74.41,ClassC,Critical
163,WH-005,DHL,Food & Beverage,859,7724.061956,141.684575,221,638,25.73,74.27,ClassC,Critical
280,WH-008,DHL,Apparel,789,7473.411648,131.920862,205,584,25.98,74.02,ClassC,Critical
164,WH-005,DHL,Furniture,1001,7626.138162,134.510919,264,737,26.37,73.63,ClassC,Critical
160,WH-005,DHL,Apparel,806,7499.476104,131.033871,216,590,26.80,73.20,ClassC,Critical
40,WH-002,DHL,Apparel,776,7453.330567,137.724678,211,565,27.19,72.81,ClassC,Critical
44,WH-002,DHL,Furniture,947,7517.816441,133.822450,259,688,27.35,72.65,ClassC,Critical
161,WH-005,DHL,Automotive,661,7670.547247,128.092057,182,479,27.53,72.47,ClassC,Critical
284,WH-008,DHL,Furniture,1012,7845.954654,134.444792,281,731,27.77,72.23,ClassC,Critical
43,WH-002,DHL,Food & Beverage,902,7512.220055,136.208137,252,650,27.94,72.06,ClassC,Critical
314,WH-008,USPS,Electronics,1711,7666.546295,138.256172,480,1231,28.05,71.95,ClassC,Critical
79,WH-002,USPS,Pharmaceuticals,983,7585.250590,139.705229,281,702,28.59,71.41,ClassC,Critical
283,WH-008,DHL,Food & Beverage,855,7229.303567,145.578596,246,609,28.77,71.23,ClassC,Critical
41,WH-002,DHL,Automotive,674,7525.062522,144.013576,197,477,29.23,70.77,ClassC,Critical
318,WH-008,USPS,Medical Supplies,719,7201.895730,139.152921,211,508,29.35,70.65,ClassC,Critical
319,WH-008,USPS,Pharmaceuticals,1113,7426.896343,134.327341,328,785,29.47,70.53,ClassC,Critical
74,WH-002,USPS,Electronics,1784,7558.858711,135.555488,529,1255,29.65,70.35,ClassC,Critical
198,WH-005,USPS,Medical Supplies,689,7757.318679,140.403454,205,484,29.75,70.25,ClassC,Critical
72,WH-002,USPS,Apparel,1088,7304.251857,129.632169,324,764,29.78,70.22,ClassC,Critical
303,WH-008,OnTrac,Pharmaceuticals,475,7562.169453,137.269537,143,332,30.11,69.89,ClassC,Critical
183,WH-005,OnTrac,Pharmaceuticals,498,7423.891627,139.500884,150,348,30.12,69.88,ClassC,Critical
194,WH-005,USPS,Electronics,1751,7360.611685,141.712153,528,1223,30.15,69.85,ClassC,Critical
78,WH-002,USPS,Medical Supplies,672,7598.000521,138.572872,207,465,30.80,69.20,ClassC,Critical
315,WH-008,USPS,Food & Beverage,1087,7636.139936,135.341978,337,750,31.00,69.00,ClassC,Critical
73,WH-002,USPS,Automotive,839,7686.222527,137.747366,263,576,31.35,68.65,ClassC,Critical
63,WH-002,OnTrac,Pharmaceuticals,516,7226.330058,135.882849,163,353,31.59,68.41,ClassC,Critical
312,WH-008,USPS,Apparel,1047,7602.786094,137.422884,332,715,31.71,68.29,ClassC,Critical
306,WH-008,UPS,Electronics,2374,7548.580910,136.897730,763,1611,32.14,67.86,ClassC,Critical
298,WH-008,OnTrac,Electronics,854,7349.585293,138.659122,275,579,32.20,67.80,ClassC,Critical
311,WH-008,UPS,Pharmaceuticals,1484,7390.098295,136.054488,478,1006,32.21,67.79,ClassC,Critical
316,WH-008,USPS,Furniture,1294,7289.713964,132.639212,417,877,32.23,67.77,ClassC,Critical
195,WH-005,USPS,Food & Beverage,1145,7366.776629,131.826690,370,775,32.31,67.69,ClassC,Critical
77,WH-002,USPS,Industrial,889,7390.302553,139.568583,288,601,32.40,67.60,ClassC,Critical
199,WH-005,USPS,Pharmaceuticals,1120,7486.900054,139.188259,364,756,32.50,67.50,ClassC,Critical
62,WH-002,OnTrac,Medical Supplies,309,7564.764757,143.421909,102,207,33.01,66.99,ClassC,Critical
58,WH-002,OnTrac,Electronics,926,7691.671782,140.608283,308,618,33.26,66.74,ClassC,Critical
310,WH-008,UPS,Medical Supplies,952,7516.381313,142.862826,317,635,33.30,66.70,ClassC,Critical
66,WH-002,UPS,Electronics,2423,7651.753727,138.377681,810,1613,33.43,66.57,ClassC,Critical
76,WH-002,USPS,Furniture,1247,7622.911628,138.900337,417,830,33.44,66.56,ClassC,Critical
191,WH-005,UPS,Pharmaceuticals,1438,7411.867288,133.698331,481,957,33.45,66.55,ClassC,Critical
197,WH-005,USPS,Industrial,864,7215.153356,137.241829,293,571,33.91,66.09,ClassC,Critical
313,WH-008,USPS,Automotive,825,7481.978582,141.703648,280,545,33.94,66.06,ClassC,Critical
71,WH-002,UPS,Pharmaceuticals,1431,7427.254326,144.357107,486,945,33.96,66.04,ClassC,Critical
186,WH-005,UPS,Electronics,2334,7613.045261,135.508625,796,1538,34.10,65.90,ClassC,Critical
59,WH-002,OnTrac,Food & Beverage,558,7260.465269,139.418172,192,366,34.41,65.59,ClassC,Critical
302,WH-008,OnTrac,Medical Supplies,353,7564.347082,133.726997,122,231,34.56,65.44,ClassC,Critical
122,WH-004,DHL,Electronics,1241,7411.095673,130.060467,430,811,34.65,65.35,ClassC,Critical
190,WH-005,UPS,Medical Supplies,926,7687.165130,134.811825,321,605,34.67,65.33,ClassC,Critical

In [92]:
products=raw_data.groupby(["Product_Category"]).agg(
    total_orders=("Shipment_ID","count"),
    wight=("Product_Weight_kg","mean"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
products["ontime_per"]=round(products['ontime_orders']/products['total_orders']*100,2)
products["delayed_per"]=round(products['delayed_orders']/products['total_orders']*100,2)

products.sort_values(ascending=True,by="ontime_per")

,Product_Category,total_orders,wight,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per
7,Pharmaceuticals,52543,249.715146,7485.304008,138.247563,24124,28419,45.91,54.09
2,Electronics,87154,249.469399,7532.942563,137.015484,40025,47129,45.92,54.08
6,Medical Supplies,34927,250.547417,7531.088463,137.837625,16086,18841,46.06,53.94
0,Apparel,52279,249.696665,7481.292657,138.229294,26448,25831,50.59,49.41
5,Industrial,43804,249.683700,7505.774175,137.866055,22221,21583,50.73,49.27
3,Food & Beverage,56741,250.262055,7469.658956,138.993748,28825,27916,50.80,49.20
4,Furniture,65138,250.074401,7518.144855,138.522222,33201,31937,50.97,49.03
1,Automotive,43742,249.232426,7508.999604,137.672683,22300,21442,50.98,49.02

In [94]:
warehouses_carriers_Route=raw_data.groupby(["Warehouse_ID","Carrier","Route_ID"]).agg(
    total_orders=("Shipment_ID","count"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
warehouses_carriers_Route["ontime_per"]=round(warehouses_carriers_Route['ontime_orders']/warehouses_carriers_Route['total_orders']*100,2)
warehouses_carriers_Route["delayed_per"]=round(warehouses_carriers_Route['delayed_orders']/warehouses_carriers_Route['total_orders']*100,2)

warehouses_carriers_Route.sort_values(ascending=True,by="ontime_per")

def classify(ontime_per):
  if ontime_per<40:
    return "ClassC","Critical"

  elif ontime_per>=40 and ontime_per<=50:
    return "ClassB","Watch"

  else:
    return "ClassA","Excellent"
warehouses_carriers_Route[["class","Performance"]]=warehouses_carriers_Route["ontime_per"].apply(lambda x:pd.Series(classify(x)))

warehouses_carriers_Route.sort_values(ascending=True,by="ontime_per").head(50)

,Warehouse_ID,Carrier,Route_ID,total_orders,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per,class,Performance
4188,WH-005,DHL,RT-0189,35,6643.704571,164.302000,1,34,2.86,97.14,ClassC,Critical
1172,WH-002,DHL,RT-0173,30,6221.643333,155.744333,1,29,3.33,96.67,ClassC,Critical
173,WH-001,DHL,RT-0174,21,5580.190952,110.190476,1,20,4.76,95.24,ClassC,Critical
1508,WH-002,OnTrac,RT-0109,21,8621.900000,98.000000,1,20,4.76,95.24,ClassC,Critical
7017,WH-008,DHL,RT-0018,35,6179.599143,156.532000,2,33,5.71,94.29,ClassC,Critical
1588,WH-002,OnTrac,RT-0189,17,6059.067647,125.254706,1,16,5.88,94.12,ClassC,Critical
1097,WH-002,DHL,RT-0098,32,6759.061563,109.223750,2,30,6.25,93.75,ClassC,Critical
1023,WH-002,DHL,RT-0024,31,7370.389032,155.566452,2,29,6.45,93.55,ClassC,Critical
1188,WH-002,DHL,RT-0189,31,6818.100968,120.960000,2,29,6.45,93.55,ClassC,Critical
7417,WH-008,OnTrac,RT-0018,15,7905.384000,117.429333,1,14,6.67,93.33,ClassC,Critical
4189,WH-005,DHL,RT-0190,29,8700.788966,150.633448,2,27,6.90,93.10,ClassC,Critical
4108,WH-005,DHL,RT-0109,28,7402.813929,190.643929,2,26,7.14,92.86,ClassC,Critical
7189,WH-008,DHL,RT-0190,41,7906.840244,117.311220,3,38,7.32,92.68,ClassC,Critical
1151,WH-002,DHL,RT-0152,40,7869.261000,132.414500,3,37,7.50,92.50,ClassC,Critical
1111,WH-002,DHL,RT-0112,37,7775.497027,121.102973,3,34,8.11,91.89,ClassC,Critical
4021,WH-005,DHL,RT-0022,36,8322.133611,139.058056,3,33,8.33,91.67,ClassC,Critical
7166,WH-008,DHL,RT-0167,44,7082.768636,124.406136,4,40,9.09,90.91,ClassC,Critical
7186,WH-008,DHL,RT-0187,32,6950.608438,156.189687,3,29,9.38,90.62,ClassC,Critical
4133,WH-005,DHL,RT-0134,31,7963.309032,119.202903,3,28,9.68,90.32,ClassC,Critical
4068,WH-005,DHL,RT-0069,31,7636.761613,140.712581,3,28,9.68,90.32,ClassC,Critical
1034,WH-002,DHL,RT-0035,20,7482.556000,132.600000,2,18,10.00,90.00,ClassC,Critical
1011,WH-002,DHL,RT-0012,20,8269.500000,159.569000,2,18,10.00,90.00,ClassC,Critical
1059,WH-002,DHL,RT-0060,20,5838.223000,202.529500,2,18,10.00,90.00,ClassC,Critical
7119,WH-008,DHL,RT-0120,30,6572.459667,142.270000,3,27,10.00,90.00,ClassC,Critical
1136,WH-002,DHL,RT-0137,29,8418.290690,112.583103,3,26,10.34,89.66,ClassC,Critical
4089,WH-005,DHL,RT-0090,19,7754.971579,127.901579,2,17,10.53,89.47,ClassC,Critical
1573,WH-002,OnTrac,RT-0174,19,6257.253684,173.337895,2,17,10.53,89.47,ClassC,Critical
4939,WH-005,USPS,RT-0140,47,8011.654043,142.089574,5,42,10.64,89.36,ClassC,Critical
4143,WH-005,DHL,RT-0144,28,7603.721429,130.552500,3,25,10.71,89.29,ClassC,Critical
7040,WH-008,DHL,RT-0041,28,7279.017143,114.869643,3,25,10.71,89.29,ClassC,Critical
1076,WH-002,DHL,RT-0077,28,7199.241786,128.197500,3,25,10.71,89.29,ClassC,Critical
7807,WH-008,USPS,RT-0008,46,9456.508696,147.255000,5,41,10.87,89.13,ClassC,Critical
1139,WH-002,DHL,RT-0140,27,8379.049630,166.237407,3,24,11.11,88.89,ClassC,Critical
7199,WH-008,DHL,RT-0200,36,7302.263889,127.584167,4,32,11.11,88.89,ClassC,Critical
4462,WH-005,OnTrac,RT-0063,18,7188.318889,128.533889,2,16,11.11,88.89,ClassC,Critical
1835,WH-002,USPS,RT-0036,45,7350.620444,124.972222,5,40,11.11,88.89,ClassC,Critical
7057,WH-008,DHL,RT-0058,35,6606.020000,152.607714,4,31,11.43,88.57,ClassC,Critical
7515,WH-008,OnTrac,RT-0116,26,5768.181154,203.709231,3,23,11.54,88.46,ClassC,Critical
1405,WH-002,OnTrac,RT-0006,17,6442.974118,130.033529,2,15,11.76,88.24,ClassC,Critical
7146,WH-008,DHL,RT-0147,34,8431.856176,117.910588,4,30,11.76,88.24,ClassC,Critical
1135,WH-002,DHL,RT-0136,34,7250.243824,125.152059,4,30,11.76,88.24,ClassC,Critical
7022,WH-008,DHL,RT-0023,34,6947.228529,126.194706,4,30,11.76,88.24,ClassC,Critical
1195,WH-002,DHL,RT-0196,34,8163.279706,143.682353,4,30,11.76,88.24,ClassC,Critical
4132,WH-005,DHL,RT-0133,34,8170.595588,172.394412,4,30,11.76,88.24,ClassC,Critical
7407,WH-008,OnTrac,RT-0008,17,6360.447059,218.718824,2,15,11.76,88.24,ClassC,Critical
4119,WH-005,DHL,RT-0120,25,7131.470000,168.456800,3,22,12.00,88.00,ClassC,Critical
4518,WH-005,OnTrac,RT-0119,25,7869.535600,164.172400,3,22,12.00,88.00,ClassC,Critical
1127,WH-002,DHL,RT-0128,33,6382.831515,164.769697,4,29,12.12,87.88,ClassC,Critical
4026,WH-005,DHL,RT-0027,49,8015.470612,126.449592,6,43,12.24,87.76,ClassC,Critical
4046,WH-005,DHL,RT-0047,32,7006.905625,117.821250,4,28,12.50,87.50,ClassC,Critical

In [98]:
customer=raw_data.groupby(["Customer_Segment"]).agg(
    total_orders=("Shipment_ID","count"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
customer["ontime_per"]=round(customer['ontime_orders']/customer['total_orders']*100,2)
customer["delayed_per"]=round(customer['delayed_orders']/customer['total_orders']*100,2)

customer.sort_values(ascending=True,by="ontime_per")

,Customer_Segment,total_orders,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per
2,Government,43556,7512.465399,138.134012,21226,22330,48.73,51.27
1,B2C,195883,7497.999221,137.588749,95715,100168,48.86,51.14
0,B2B,196889,7510.984041,138.398484,96289,100600,48.91,51.09

Monthly Analysis

In [103]:
raw_data["Order_Date"]=pd.to_datetime(raw_data["Order_Date"])
raw_data["Promised_Delivery_Date"]=pd.to_datetime(raw_data["Promised_Delivery_Date"])
raw_data["Actual_Delivery_Date"]=pd.to_datetime(raw_data["Actual_Delivery_Date"])

In [133]:
avg_delay=raw_data['Actual_Delivery_Date']-raw_data['Promised_Delivery_Date']
raw_data["avg_delay"]=avg_delay.dt.days

In [134]:
warehouses_carriers_Route=raw_data.groupby(["Warehouse_ID","Carrier"]).agg(
    total_orders=("Shipment_ID","count"),
    avg_delay=("avg_delay","mean"),
    max_delay=("avg_delay","max"),
    min_delay=("avg_delay","min"),
    order_value=("Order_Value","mean"),
    shippingcost=("Shipping_Cost","mean"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())
).reset_index()
warehouses_carriers_Route["ontime_per"]=round(warehouses_carriers_Route['ontime_orders']/warehouses_carriers_Route['total_orders']*100,2)
warehouses_carriers_Route["delayed_per"]=round(warehouses_carriers_Route['delayed_orders']/warehouses_carriers_Route['total_orders']*100,2)

warehouses_carriers_Route.sort_values(ascending=True,by="ontime_per")

def classify(ontime_per):
  if ontime_per<40:
    return "ClassC","Critical"

  elif ontime_per>=40 and ontime_per<=50:
    return "ClassB","Watch"

  else:
    return "ClassA","Excellent"
warehouses_carriers_Route[["class","Performance"]]=warehouses_carriers_Route["ontime_per"].apply(lambda x:pd.Series(classify(x)))

warehouses_carriers_Route.sort_values(ascending=True,by="ontime_per").head(50)

,Warehouse_ID,Carrier,total_orders,avg_delay,max_delay,min_delay,order_value,shippingcost,ontime_orders,delayed_orders,ontime_per,delayed_per,class,Performance
20,WH-005,DHL,6642,6.598916,62,-3,7488.673528,133.926939,1649,4993,24.83,75.17,ClassC,Critical
5,WH-002,DHL,6485,6.541403,60,-3,7511.810244,136.953062,1634,4851,25.20,74.80,ClassC,Critical
35,WH-008,DHL,6586,6.516095,61,-3,7534.577083,137.441297,1686,4900,25.60,74.40,ClassC,Critical
39,WH-008,USPS,8621,6.044078,61,-3,7495.187180,136.623843,2673,5948,31.01,68.99,ClassC,Critical
9,WH-002,USPS,8651,6.002081,58,-3,7534.979060,136.934402,2709,5942,31.31,68.69,ClassC,Critical
24,WH-005,USPS,8794,5.799636,63,-3,7461.065650,137.268129,2903,5891,33.01,66.99,ClassC,Critical
7,WH-002,OnTrac,4357,5.476475,61,-3,7499.782447,137.947165,1527,2830,35.05,64.95,ClassC,Critical
37,WH-008,OnTrac,4265,5.549824,58,-3,7438.714851,137.126014,1511,2754,35.43,64.57,ClassC,Critical
38,WH-008,UPS,11865,5.311083,60,-3,7459.944592,136.350013,4318,7547,36.39,63.61,ClassC,Critical
22,WH-005,OnTrac,4369,5.390936,60,-3,7489.702456,137.059169,1610,2759,36.85,63.15,ClassC,Critical
23,WH-005,UPS,11747,5.381033,60,-3,7534.629864,136.077347,4330,7417,36.86,63.14,ClassC,Critical
8,WH-002,UPS,11807,5.268654,63,-3,7491.327472,138.311336,4374,7433,37.05,62.95,ClassC,Critical
6,WH-002,FedEx,12079,5.008362,61,-3,7545.534307,138.634747,4827,7252,39.96,60.04,ClassC,Critical
21,WH-005,FedEx,12000,5.022583,62,-3,7546.495701,138.275778,4808,7192,40.07,59.93,ClassB,Watch
36,WH-008,FedEx,12112,4.878303,59,-3,7470.873202,138.111195,4950,7162,40.87,59.13,ClassB,Watch
15,WH-004,DHL,6532,4.901255,59,-3,7487.496549,135.977610,2682,3850,41.06,58.94,ClassB,Watch
0,WH-001,DHL,6559,4.896173,59,-3,7486.987196,134.662863,2718,3841,41.44,58.56,ClassB,Watch
10,WH-003,DHL,6460,4.718885,59,-3,7395.693972,135.829847,2719,3741,42.09,57.91,ClassB,Watch
45,WH-010,DHL,6507,4.819733,58,-3,7501.766010,139.131328,2741,3766,42.12,57.88,ClassB,Watch
30,WH-007,DHL,6496,4.841133,60,-3,7502.405182,138.679711,2741,3755,42.20,57.80,ClassB,Watch
25,WH-006,DHL,6540,4.699083,57,-3,7660.084265,137.951934,2766,3774,42.29,57.71,ClassB,Watch
40,WH-009,DHL,6637,4.747175,60,-3,7626.477945,140.030872,2836,3801,42.73,57.27,ClassB,Watch
4,WH-001,USPS,8960,3.744866,59,-3,7540.343215,139.031886,4585,4375,51.17,48.83,ClassA,Excellent
14,WH-003,USPS,8754,3.689742,63,-3,7573.743920,137.659488,4504,4250,51.45,48.55,ClassA,Excellent
34,WH-007,USPS,8748,3.745770,57,-3,7536.564815,138.062370,4507,4241,51.52,48.48,ClassA,Excellent
49,WH-010,USPS,8873,3.773132,58,-3,7439.971082,136.561364,4583,4290,51.65,48.35,ClassA,Excellent
19,WH-004,USPS,8664,3.733380,58,-3,7489.457163,137.547313,4498,4166,51.92,48.08,ClassA,Excellent
29,WH-006,USPS,8802,3.678369,60,-3,7580.452958,138.347305,4605,4197,52.32,47.68,ClassA,Excellent
44,WH-009,USPS,8847,3.647225,61,-3,7457.018446,138.802613,4639,4208,52.44,47.56,ClassA,Excellent
27,WH-006,OnTrac,4420,3.406335,57,-3,7523.581916,141.313342,2420,2000,54.75,45.25,ClassA,Excellent
12,WH-003,OnTrac,4404,3.398501,56,-3,7529.477548,135.485817,2431,1973,55.20,44.80,ClassA,Excellent
17,WH-004,OnTrac,4382,3.234368,57,-3,7559.642469,138.697549,2435,1947,55.57,44.43,ClassA,Excellent
42,WH-009,OnTrac,4359,3.289287,56,-3,7451.926797,136.934769,2437,1922,55.91,44.09,ClassA,Excellent
2,WH-001,OnTrac,4249,3.249941,58,-3,7637.601525,140.963770,2390,1859,56.25,43.75,ClassA,Excellent
18,WH-004,UPS,11523,3.194047,59,-3,7534.882332,139.148783,6568,4955,57.00,43.00,ClassA,Excellent
32,WH-007,OnTrac,4388,3.131039,56,-3,7379.154043,138.675672,2511,1877,57.22,42.78,ClassA,Excellent
47,WH-010,OnTrac,4513,3.129182,58,-3,7468.188626,138.260716,2583,1930,57.23,42.77,ClassA,Excellent
28,WH-006,UPS,11733,3.061706,58,-3,7389.576241,137.639634,6722,5011,57.29,42.71,ClassA,Excellent
3,WH-001,UPS,11744,3.135473,58,-3,7514.824503,137.548773,6756,4988,57.53,42.47,ClassA,Excellent
33,WH-007,UPS,11830,3.025782,59,-3,7508.677007,138.706322,6830,5000,57.73,42.27,ClassA,Excellent
48,WH-010,UPS,11861,3.057162,57,-3,7536.665768,138.782432,6852,5009,57.77,42.23,ClassA,Excellent
43,WH-009,UPS,11956,3.006273,60,-3,7449.648939,138.143142,6942,5014,58.06,41.94,ClassA,Excellent
13,WH-003,UPS,11821,3.059809,59,-3,7497.619952,138.449273,6867,4954,58.09,41.91,ClassA,Excellent
46,WH-010,FedEx,12192,2.812008,60,-3,7529.136568,138.691751,7336,4856,60.17,39.83,ClassA,Excellent
1,WH-001,FedEx,12185,2.766352,64,-3,7478.390475,139.618332,7388,4797,60.63,39.37,ClassA,Excellent
11,WH-003,FedEx,12258,2.743270,57,-3,7496.045804,139.875252,7434,4824,60.65,39.35,ClassA,Excellent
16,WH-004,FedEx,12083,2.751386,60,-3,7453.816335,137.410771,7329,4754,60.66,39.34,ClassA,Excellent
26,WH-006,FedEx,12159,2.662637,57,-3,7500.509150,139.372501,7390,4769,60.78,39.22,ClassA,Excellent
31,WH-007,FedEx,12111,2.673437,59,-3,7586.116873,138.513660,7384,4727,60.97,39.03,ClassA,Excellent
41,WH-009,FedEx,12398,2.734796,59,-3,7489.214478,139.039363,7592,4806,61.24,38.76,ClassA,Excellent

In [135]:
raw_data["year"]=raw_data['Order_Date'].dt.year
raw_data["month"]=raw_data['Order_Date'].dt.month
raw_data["month_name"]=raw_data['Order_Date'].dt.strftime("%b")
raw_data["quater"]=raw_data['Order_Date'].dt.quarter


raw_data["day"]=raw_data['Order_Date'].dt.day
raw_data["day_name"]=raw_data['Order_Date'].dt.strftime("%a")

In [136]:
monthly_ontime=raw_data.groupby(["year","month","month_name"]).agg(
    total_orders=("Shipment_ID","count"),
    ontime_orders=("On_Time_Flag",lambda x:(x==1).sum()),
    delayed_orders=("On_Time_Flag",lambda x:(x==0).sum())).reset_index()
monthly_ontime["ontime_per"]=round(monthly_ontime['ontime_orders']/monthly_ontime['total_orders']*100,2)
monthly_ontime["delayed_per"]=round(monthly_ontime['delayed_orders']/monthly_ontime['total_orders']*100,2)
monthly_ontime.loc[monthly_ontime["ontime_per"]<=40]

,year,month,month_name,total_orders,ontime_orders,delayed_orders,ontime_per,delayed_per
10,2021,11,Nov,9046,2980,6066,32.94,67.06
11,2021,12,Dec,9221,2990,6231,32.43,67.57
22,2022,11,Nov,9069,2944,6125,32.46,67.54
23,2022,12,Dec,9287,3123,6164,33.63,66.37
34,2023,11,Nov,8996,2932,6064,32.59,67.41
35,2023,12,Dec,9313,3037,6276,32.61,67.39
46,2024,11,Nov,8944,2931,6013,32.77,67.23
47,2024,12,Dec,9332,3089,6243,33.10,66.90

In [141]:
quarterly = raw_data.groupby('quater').agg(
    Total=('Shipment_ID','count'),
    OnTime_Rate=('On_Time_Flag', lambda x: x.mean()*100),
    delayed_per=('On_Time_Flag', lambda x: 100 - x.mean()*100)
).reset_index()
print(quarterly)

   quater   Total  OnTime_Rate  delayed_per
0       1  107950    47.641501    52.358499
1       2  108436    54.389686    45.610314
2       3  109778    53.049791    46.950209
3       4  110164    40.472387    59.527613

In [137]:
delayed = raw_data[raw_data['On_Time_Flag']==0]
print(f"Total order value at risk: ${delayed['Order_Value'].sum():,.2f}")
print(f"Total shipping cost wasted: ${delayed['Shipping_Cost'].sum():,.2f}")

Total order value at risk: $1,676,069,083.73
Total shipping cost wasted: $30,763,303.55

Final check on nulls or dupicates or any changes

In [142]:
print(f" nulls:{raw_data.isnull().sum()},dupicates:{raw_data.duplicated().sum()},shape:{raw_data.shape}")
print(f"{raw_data.info()} ,{raw_data.describe()}")

 nulls:Shipment_ID               0
Order_Date                0
Promised_Delivery_Date    0
Actual_Delivery_Date      0
Delay_Days                0
Delay_Status              0
On_Time_Flag              0
Origin_City               0
Origin_State              0
Origin_Region             0
Destination_City          0
Destination_State         0
Destination_Region        0
Route_ID                  0
Distance_Miles            0
Warehouse_ID              0
Warehouse_City            0
Warehouse_State           0
Carrier                   0
Ship_Mode                 0
Product_Category          0
Product_Weight_kg         0
Order_Value               0
Shipping_Cost             0
Customer_Segment          0
Customer_ID               0
Weather_Condition         0
Traffic_Condition         0
avg_delay                 0
year                      0
month                     0
day                       0
quater                    0
month_name                0
day_name                  0
dtype: int64,dupicates:0,shape:(436328, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 436328 entries, 0 to 450799
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Shipment_ID             436328 non-null  object
 1   Order_Date              436328 non-null  datetime64[ns]
 2   Promised_Delivery_Date  436328 non-null  datetime64[ns]
 3   Actual_Delivery_Date    436328 non-null  datetime64[ns]
 4   Delay_Days              436328 non-null  float64
 5   Delay_Status            436328 non-null  object
 6   On_Time_Flag            436328 non-null  float64
 7   Origin_City             436328 non-null  object
 8   Origin_State            436328 non-null  object
 9   Origin_Region           436328 non-null  object
 10  Destination_City        436328 non-null  object
 11  Destination_State       436328 non-null  object
 12  Destination_Region      436328 non-null  object
 13  Route_ID                436328 non-null  object
 14  Distance_Miles          436328 non-null  int64
 15  Warehouse_ID            436328 non-null  object
 16  Warehouse_City          436328 non-null  object
 17  Warehouse_State         436328 non-null  object
 18  Carrier                 436328 non-null  object
 19  Ship_Mode               436328 non-null  object
 20  Product_Category        436328 non-null  object
 21  Product_Weight_kg       436328 non-null  float64
 22  Order_Value             436328 non-null  float64
 23  Shipping_Cost           436328 non-null  float64
 24  Customer_Segment        436328 non-null  object
 25  Customer_ID             436328 non-null  object
 26  Weather_Condition       436328 non-null  object
 27  Traffic_Condition       436328 non-null  object
 28  avg_delay               436328 non-null  int64
 29  year                    436328 non-null  int32
 30  month                   436328 non-null  int32
 31  day                     436328 non-null  int32
 32  quater                  436328 non-null  int32
 33  month_name              436328 non-null  object
 34  day_name                436328 non-null  object
dtypes: datetime64[ns](3), float64(5), int32(4), int64(2), object(21)
memory usage: 113.2+ MB
None ,                          Order_Date         Promised_Delivery_Date  \
count                         436328                         436328
mean   2022-12-31 16:01:26.665077504  2023-01-05 11:20:36.676995072
min              2021-01-01 00:00:00            2021-01-02 00:00:00
25%              2022-01-01 00:00:00            2022-01-05 00:00:00
50%              2022-12-31 00:00:00            2023-01-05 00:00:00
75%              2024-01-01 00:00:00            2024-01-06 00:00:00
max              2024-12-31 00:00:00            2025-01-10 00:00:00
std                              NaN                            NaN

                Actual_Delivery_Date     Delay_Days   On_Time_Flag  \
count                         436328  436328.000000  436328.000000
mean   2023-01-09 12:08:19.396783872       4.033133       0.488692
min              2020-12-30 00:00:00      -3.000000       0.000000
25%              2022-01-11 00:00:00      -1.000000       0.000000
50%              2023-01-10 00:00:00       2.000000       0.000000
75%              2024-01-11 00:00:00       9.000000       1.000000
max              2025-02-28 00:00:00      64.000000       1.000000
std                              NaN       7.218620       0.499873

       Distance_Miles  Product_Weight_kg    Order_Value  Shipping_Cost  \
count   436328.000000      436328.000000  436328.000000  436328.000000
mean      1523.565476         249.803670    7505.302573     138.008565
min         50.000000           0.500000      20.030000      10.060000
25%        784.000000         124.720000    3765.030000      53.120000
50%       1526.000000         249.580000    7505.980000      89.960000
75%       2260.000000         375.100000   11248.632500     166.280000
max       3000.000000         500.000000   14999.950000     871.870000
std        852.216783         144.339745    4323.329353     133.362195

           avg_delay           year          month            day  \
count  436328.000000  436328.000000  436328.000000  436328.000000
mean        4.033133    2022.499860       6.525355      15.749814
min        -3.000000    2021.000000       1.000000       1.000000
25%        -1.000000    2022.000000       4.000000       8.000000
50%         2.000000    2022.000000       7.000000      16.000000
75%         9.000000    2024.000000      10.000000      23.000000
max        64.000000    2024.000000      12.000000      31.000000
std         7.218620       1.118078       3.450689       8.796123

              quater
count  436328.000000
mean        2.509149
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
std         1.117895

In [143]:
raw_data.to_csv("Cleaned_data_supply_chain.csv",index=False)